language: php
php:
  - 7.0
  - 7.1
before_script:
  - composer self-update
  - composer install
  - stty cols 80 # weird Travis CI issue with PHPUnit ResultPrinter https://github.com/sebastianbergmann/phpunit/issues/1976
script:
  - composer lint
  - composer cs
  - composer test
  - composer phpstan
after_script:
  - php vendor/bin/coveralls -v
